name: resumate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  sentry_flutter: ^9.9.1
  equatable: ^2.0.7
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_markdown: ^0.7.7+1
  google_fonts: ^6.3.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  pdf: ^3.11.3
  printing: ^5.14.2
  supabase_flutter: ^2.3.4
  uuid: ^4.5.2
  syncfusion_flutter_pdf: ^26.1.35
  docx_to_text: ^1.0.1
  archive: ^3.6.1
  timeago: ^3.7.1

dev_dependencies:
  sentry_dart_plugin: ^3.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.3
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: resume_builder
  org: flutter-developer-sb
